Algoritmo "senha_fixa"

Var

   senha, correta : inteiro
   
Inicio

      escreva("Digite a senha: ")
      leia(senha)
      
      correta <- 2002
      //cont <- 0
      
      
      enquanto senha <> correta faça

         escreva("Senha Invalida! Tente novamente: ")
         leia(senha)
         
      fimenquanto
      
      
      escreval("Acesso permitido!")


Fimalgoritmo